version: '3.8'
services:
  app:
    image: frontend
    build:
      context: ./frontend
      target: dev  # production
      dockerfile: Dockerfile
    volumes:
        - appvol_csi29:/frontend/app
        - /frontend/app/node_modules
        - /frontend/app/.next
    ports:
      - "3000:3000"
  
  backend:
    image: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - server-side

  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - server-side
    ports:  # dev/debug only: allows to interact w/ DB from host, but you must set DATABASE_URL w/ port 5555
      - 5555:5432
    volumes:
      - appvol_csi29_data:/var/lib/postgresql/data


volumes:
  # DELETE them from your dev environment (PC) if you don't want to keep them
  # see `docker volume ls`, `docker volume rm`, `docker volume prune`
  appvol_csi29:
  appvol_csi29_data:

networks:
  server-side: